language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests tests.unit
deploy:
  provider: pypi
  password:
    secure: AKe2YGVhUzK3PKGv4TSCibO9L+eiKT+4EPKqvUrn0QvBKQ9Du7d/X6mo1IQFqp1m9vekDVX8LBWp9Phn//3ICTMaqj37xzy4aQLhTYwsjNwpXKLn5biz2WCrouSD9jUrcTUsOscwgXRdyph2s85qeHaHe4wvDaptA95/pF4s8Knif7bcHL5n9w0Y6X3wGc8271LSD5ypYlszIy0rZSGjrdbNkzoQVuKpkalU0iUmDRjRHbbM91mgyKezdM079xmRmkEL/JNOARy/cO7gJVgxO5oNaJNGW8KxqNS6T8FfYhG2bZ+FFn71D8T6jC0s86QXN6NrBeIlAMh6tQf2CxlBHNSYFHT5Wlrf8VOEROMyN7CkhOasOc5Anw09m/6TfDz+T60g+2Dj+qjBibwp/GmTX/YFDuOx9A96pttR8qoDCHHFWa/+/hEh+6rLd0r6E+Ehrli8DaYZeLoKPMYCQQZ65V1DH6JawhwCE8hodw8AhA+ahjZUz5ajiLIwmHd0ugsMPC8izHC7BKjCYEhPMWxjj897otkS98AE7OwXyCqBwsV5IiDacY+gO7O4wrvKFtsiOK8Q/8ltD93QW86NrldBjFWWqU8N8Qit3ZLgYFGDd5YpR6FgpYxpYnuTHaITZuaRgo0kmTSDA0Y6rt9UMZ2U1WztulRp+b88SWi6CiTZh18=
  user:
    secure: c72G2VfZsqqHYSllqNvwv9i2aB1fxg9CohUrD+NrNcGB4uLYbgQYUbfRdxYKBl4GZxbNp2VXyiFowmAMG1Q6MiaHXpxIRboYbzm078EDjE0MxFHaPaLJFkYS54pF38wjeBy954SXNMOfrCPpkyDiPC4FwgIP2keh6+ZMreXym3Ob0UkW4d9X1cHpuDDcVFtwKxBMvWGZfceeukkjmr0rLum0Hh+2TQiby40n3mi4KnsPHZv6+90CiYM+N3xMDWw5OxkpClSqNMbN1gOGl+L8eTPNX+j9yqptrkNdlDqzRlbPFiivdJ8eSoUV1PRDz8rri5+W5RyambbtMywMUjP9dr25yHMsPT1r8RqUQRlxU252OOTOL/DYPFaNwfU2y3LqcNG5qZlRLEJl1pCXktOKbu00ITPZKPNxGFMv0oW3E/OxylhMbCMcsVuANilagi9BnGvZ//2mKypyIpUjbwpu4s+LAYFPYh9rWwIIenprhoSj4BKroHtpi/UfC3HFQ/DAbYW3FEgcRH/2eucEW+bT/8l6dr3A6aZSmACaArE2Rjrx32K3Qb63YqDVpdepTsfsvQ0ps7KkH0AQ5X6ymXvvPcMrvG8r3svTSYdJLifKZAkrRi2aNxaB3gpVu86tElS8f9NIyrHGscYz87MlzL+UvcyX2V5dH8eiRTzO1N8D6UU=
  on:
    tags: true
notifications:
  hipchat:
    rooms:
      secure: vhOLmvUqhdCh8zaYBgX8ZUwh/QL4TezVEMFVE+9giCU8wZyNHFckiiq/Zu1CD+OpuknJNrlF1Qt3jQHBl3SbaBcMVMWh5AqoUAm8uZS4GAB6rN5bg2GibkoUdlkx5gCkq4zwgP9C6kmLsVKarLTxaDCjrSa1Yjme245NB6n3BHwxs8OuZ3MU2x/DdeGWYgMO29N8/z7G7Pci5RF63Y9VoCHEVMNNOQnlAbtFtVaFBcpQFkEhlr5x8MfUVZDus8wFvn/MedsXaVtuMSPB6sjNxCpdDFTirb46HHYj42fFGUa65yK9m7Ym9xMwrQqpZoyPxRZxBW6uBmoLiA4RrBDuE6oawBUw6SOGjyqwc3HcJMdpz11VZH78mo/q4gLCkZvEKDEHD5p1tBlPDo2o1yCVyWCwK7Tq1QxiwtiFdjOJYf3KGeTg4qUP7MiI0hx9rXKdo96XZ6rCB/iCQufDxqkmXOsrgmEmVAwU+L5QT2EN0JzciQ9TG0hx7zlRp/YaZh3TJfRvwytujJx/JUEetC5NDQbgUdXmKXprUI8saq8Ad7uRvjB2qEEsQfdUTB/6h7mearbya9xPrIJaaXaW5c+zhZ0PLGZkRhM/6OXTrKerJXP8JedwAlBvNRonKozQAZJeYGEp0Ppp7oas+MOXsAWhUlwoFWop9W50opvRPRrNPZY=
