language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests tests.unit
deploy:
  provider: pypi
  password:
    secure: yIVgTFoAFC90XmOkURRheJzjDsekgtxNBt9lkS3fz++zSky5P2dlsOHkjlDynKiLCmz372SfWLlfrHHelm6gxBlt4e/zM+B5QT5s69fX19TnWbsaVIBscAFBhh4upiKIB7CjR3+mVDmJbTucebmHTrZhnndxYGG7A1ymVE2iJDrb2wXGDur4Qz4sdaOqLiA+6k5P6bVKbjnGDLVQ+ZxLxSCCXBHk/rARAElEG8JddtyRcFNJsIs16pEj8TtvSzSd+UuTxF3e33Bze5zRQ6yCUcLjXvAZHN78Su4K0tS3eYiIVL/+TjqnN1ZdjFIvHPH6+BMUZphZ0++TlYHNCVm60tJealvaDPUSqhtWiyduXi/ZriEd5nG1fadNff4OSZH7Ml96y2pI/r3VyN+JdA3Ncc4FbHa2mM55E+mODQXq+GSzHzxABX+rbAEMfoBtBCUp752pr0vnpplKQBex+uhez4IsQs58OOIxC8R7d7QW8VCSFio6OHdYuXY7Lo3d5KR+bNQO+z3WoewsvKrEv7Hx/gqsxahd8re05HS28IoZhveDDTvpYwWQSa59VuScNZGpCmKAHXNSJBtfOTcq53Opb5Y78B+W6al+NiIkEbRMyiz5FQYn+MCxvI/HTV7vWoFzxcO3iGWz4vs/Cc50VCd/dzMwS7Kt3thO8k2cY3Lmbdw=
  user:
    secure: mCU3mQ438kHE/5woONF33Ws/yWFhgPUU72wdI22M5sV2Uwe727oA7miN8j/mxoIHkAxmH+b04ZQaz6gWZCD3fwtTh3Ov+gkVkJogGcM9Xoe+0PKmVMM2bN4uxNZ9vK0UweYntmeqx4t7AIGtr2WWjI9FR6R+U0bXuDpDbz/aH8W7wnD5xACgm6QThiq4lGFhMvaZVjBSZRIkSHdPJXDxAaJn1O1DKWekYN7+8SgPVavmJI6ysJWdiZcmmT1Nw03wIUmId87Ex06eN1GYtZLsVWnP1ht0WGP59kh5YQ+/4p9UD20OOmGBkXKud2aDfYYLfO0xrxmWleQtof4lEUkaQ4FQjmrd9onQ0nOFrtX/IA0zRENcr77It7dRlNdyEHIyS3ANIMFvPvLgEgKfN+EaaQ7iK++AAJkemB0tpDrH/J/HNQxxNJ77Zt+ubxlpI0c26gXbWs/uyNs6ZDcl9Bop9thDWhgcfU4rhlqNZG+TstP8025jxj6skVwXK0zk7hsNHJrQmrLaDgP+6OaypOjnDgcfcAY0H9Ea8W0KBx7GP2QV2Xr6i+3wcxXnhsOf1TxCKi+hf+ygujD2YaZS1fdyQqdA/vLJxKSVFQVY8YcxaFZRW3ciiIYrEq7By5udjv9o2ns8ZAaS+ODh68h1+FCr/UrL+SsupOHrl/NgZZD4eu0=
  on:
    tags: true
notifications:
  hipchat:
    rooms:
      secure: GtG18B77T0XRtwyqiVpaQjsi+dRY94pQfpz6XgSuhVLUpcD8C1kyHI1VwLvgEGlW6V/TuN9QlUa/RqCnWHT9DlYVziYn3j4kLHWO6WXrWBfTsGhLOj1qwsmw/H/0W5X3SgRa6gbH4/Wj9ImDsGhiOEGkKvQqtzSOv5d24tclochspprno7UFvnFRfvw355T41L9wQw/+RA/Z+K9ziFgMIelfhtXGZoEQMqokvrbKe3qoJDf7ERuq39fQxpruc5mVH6u6YOPDkSaC0Wgc/hjLfC9Os+soJpz+VNpQ1GgL3aGxPBISVr17R93H0ANiWsk5BzdCmTOfHLvuDV/xmEMLfBXN6u86fJVzswSn6AeouBprk3j4MhmbJdMMSEiNVWpiDfTPoltKMBRJ1pcdIdq59eZcV8RYfVWp+J59O4eza4N8/UAuqTZ/QHImSzHeN+CMZwLvO4m8SgaSjx2tRQSWev0VEL1BbeT1470OsHJ17DpIcF9okYM69DGa6Tdlprrq8hLNc+oxburOghwBtQfaBWclXowfUgLxx0QNsErD60x9+EfHw7JMYCrORVtONc5nh+GtSRFVG2cbaBPvht0+xdVXFz5pWPoJdLL2bFJ/NnbgjuBb50KrE8kSysmqFHIdtD/KiElKy+oZVdDr5EhgTot9xih13XsiDNAME/RecWs=
