language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script: nosetests tests.unit
deploy:
  provider: pypi
  password:
    secure: AKe2YGVhUzK3PKGv4TSCibO9L+eiKT+4EPKqvUrn0QvBKQ9Du7d/X6mo1IQFqp1m9vekDVX8LBWp9Phn//3ICTMaqj37xzy4aQLhTYwsjNwpXKLn5biz2WCrouSD9jUrcTUsOscwgXRdyph2s85qeHaHe4wvDaptA95/pF4s8Knif7bcHL5n9w0Y6X3wGc8271LSD5ypYlszIy0rZSGjrdbNkzoQVuKpkalU0iUmDRjRHbbM91mgyKezdM079xmRmkEL/JNOARy/cO7gJVgxO5oNaJNGW8KxqNS6T8FfYhG2bZ+FFn71D8T6jC0s86QXN6NrBeIlAMh6tQf2CxlBHNSYFHT5Wlrf8VOEROMyN7CkhOasOc5Anw09m/6TfDz+T60g+2Dj+qjBibwp/GmTX/YFDuOx9A96pttR8qoDCHHFWa/+/hEh+6rLd0r6E+Ehrli8DaYZeLoKPMYCQQZ65V1DH6JawhwCE8hodw8AhA+ahjZUz5ajiLIwmHd0ugsMPC8izHC7BKjCYEhPMWxjj897otkS98AE7OwXyCqBwsV5IiDacY+gO7O4wrvKFtsiOK8Q/8ltD93QW86NrldBjFWWqU8N8Qit3ZLgYFGDd5YpR6FgpYxpYnuTHaITZuaRgo0kmTSDA0Y6rt9UMZ2U1WztulRp+b88SWi6CiTZh18=
  user:
    secure: c72G2VfZsqqHYSllqNvwv9i2aB1fxg9CohUrD+NrNcGB4uLYbgQYUbfRdxYKBl4GZxbNp2VXyiFowmAMG1Q6MiaHXpxIRboYbzm078EDjE0MxFHaPaLJFkYS54pF38wjeBy954SXNMOfrCPpkyDiPC4FwgIP2keh6+ZMreXym3Ob0UkW4d9X1cHpuDDcVFtwKxBMvWGZfceeukkjmr0rLum0Hh+2TQiby40n3mi4KnsPHZv6+90CiYM+N3xMDWw5OxkpClSqNMbN1gOGl+L8eTPNX+j9yqptrkNdlDqzRlbPFiivdJ8eSoUV1PRDz8rri5+W5RyambbtMywMUjP9dr25yHMsPT1r8RqUQRlxU252OOTOL/DYPFaNwfU2y3LqcNG5qZlRLEJl1pCXktOKbu00ITPZKPNxGFMv0oW3E/OxylhMbCMcsVuANilagi9BnGvZ//2mKypyIpUjbwpu4s+LAYFPYh9rWwIIenprhoSj4BKroHtpi/UfC3HFQ/DAbYW3FEgcRH/2eucEW+bT/8l6dr3A6aZSmACaArE2Rjrx32K3Qb63YqDVpdepTsfsvQ0ps7KkH0AQ5X6ymXvvPcMrvG8r3svTSYdJLifKZAkrRi2aNxaB3gpVu86tElS8f9NIyrHGscYz87MlzL+UvcyX2V5dH8eiRTzO1N8D6UU=
  on:
    tags: true
notifications:
  hipchat:
    rooms:
      secure: HzbCTcVE6xhGQFSU0v03b96Z2uaAS6ETQHfLtu+1INscqbzGhXELFS62M2WJGJ1s2ueuY17/vXEotPS5rn2PddQJnDB23Q2U7lZPjGJbgvPAnRx6B1Bc//Gmb/YZyiUpc1oh4F42mA9lMagNoEsyCMzrQ8dFxosag3lxkeC+iNuaRUvneBGnS0ntPxSGMA3DupsJJou8FeQPerSVUy22aebMEziOFpoU+5pfg3eQAK8WDiOF7B7Bo5PBb16gIIdkhqF+eeHxdcQaeqxGolGC/iMqemW9zsejGoIqb/KHZk8OyUxWM07D9q4qHi2uThlgJjscIeiCl3wzcEBKX9TjeXWPy9BLFkSO//XZOgq94JP4Tc1WY7Ek3ALbHrDZllGhi/hJJih7oDXvOmI0RKoQvj32Tk+AuKzbpia8TXSKulcp3VkewvYwxH48WPMt4P+rsGhXrKWjT6JFlbWdLpDsB6YF11cBAfnjn7DCfQSBc39s47KRr/IfQmpJRRbHv/clH69iGhaB75Q/e1xWSdduQ3F9jOHZUuB3i0NnLZ5Ne+hn22l3OEsRbJXu/XnZO3qgneqm5i/VaEiPsCJNlbD8X6Vs+ynUzgrupXDavj3aipxQdZhxla+6V1qHNUA9jN04DWvlVekTA35nGWY9Qxy0nVhSKPPKFxzTdMEz0IjSgF4=
